### PR TITLE
Dev v0.3

### PR DESCRIPTION
**Pull request by generationmake**
development for version 0.3

### CODE REVIEW

**Comment by generationmake** [comment]
Hi @aentinger 
I updated the design data and added a hole for cooling.
Could you please check the data?
Thanks

**Comment by aentinger** [comment]
Looking good. Will commence test print :+1:

**Review by aentinger — APPROVED** [review]
LGTM 👍 

The lids could go down a bit more (another mm or so) but the rest is fine 🚀

**Comment by aentinger** [comment]
IMG_20231102_062122_244
IMG_20231102_062116_535
IMG_20231102_062108_035
IMG_20231102_060309_161

**Review by aentinger — APPROVED** [review]

**Pull request merged**
