### PR TITLE
Dev v0.2

### PR DESCRIPTION
**Pull request by generationmake**
updates for next revision

### CODE REVIEW

**Comment by generationmake** [comment]
Hi @aentinger 
please review and test.

**Comment by aentinger** [comment]
Hi @generationmake ☕ 👋 

Thank you for your effort! I see a possible problem with the mounting screws blocking the cable for Gigabit-Ethernet but I suppose a test print will show more.

I'll commence a test print as soon as I get back into my office.

**Comment by aentinger** [comment]
Pictures from BOT only:

IMG_20230727_065429_507
IMG_20230727_065409_995
IMG_20230727_065359_819
IMG_20230727_065353_244
IMG_20230727_065334_563

**Comment by aentinger** [comment]
Pictures from TOP:

IMG_20230727_102822_133
IMG_20230727_102810_983
IMG_20230727_102759_042
IMG_20230727_102743_634

**Review by aentinger — APPROVED** [review]
LGTM :+1: for solving feature requests documented. I'll open new issues for the new feature requests. This can be merged. Thank you @generationmake :coffee: :wave:

**Pull request merged**
